# Generated by Django 4.1.7 on 2023-02-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('postcode', models.CharField(max_length=10)),
                ('property_type', models.CharField(max_length=1)),
                ('new_building', models.BooleanField()),
                ('duration', models.CharField(max_length=1)),
                ('paon', models.CharField(max_length=256)),
                ('saon', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('locality', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('district', models.CharField(max_length=256)),
                ('county', models.CharField(max_length=256)),
                ('category_type', models.CharField(max_length=128)),
                ('record_status', models.CharField(max_length=128)),
            ],
        ),
    ]
